### ISSUE TITLE
Frequent "TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by nimuxoha** [kepstin/magicisrc#17]
Normally I open magicisrc from Harmony after adding new releases but very often when submitting ISRCs or just loading the page I get this error:
`When fetching MusicBrainz release: TypeError: Failed to fetch`

It's very frustrating having to repeatedly reload the page in hopes there won't be an error.  I suspect it's related to the MB API rate-limit and me going too fast. Might there be a another solution?

**Comment by kepstin** [comment]
I doubt that rate limiting is the issue. I've tried on purpose to hit rate limits in magicisrc and i simply haven't been able to reload the page fast enough to cause any issues. Also, the requests that magicisrc makes to musicbrainz can be cached by the browser, which reduces issues.

If you're still able to reproduce this problem, I would appreciate a screenshot of the browser web inspector "Network" tab with the request to `musicbrainz.org/ws/2/...` selected so i can see what's going wrong with the request. That should show the response status code and headers.

**Comment by nimuxoha** [comment]
It happens mostly when I add many releases and open magicisrc for each one. I'll try to reproduce it with network logs at the weekend if possible.

**Comment by kepstin** [comment]
The musicbrainz api normally allows 1 request per second, but you can exceed that a bit temporarily as long as you stay with ~1/s on average. I suppose it might be possible to click extremely quickly and open multiple copies of magicisrc within a second, but it would be difficult to hit the rate limit otherwise unless you're unfortunate enough to have your ip address in a range which has been flagged for abuse and has a lower rate limit applied. (if this has happened to you, you might be able to contact musicbrainz to get this cleared).

I'd be interested in the network logs to determine what the exact cause of the error you're hitting is. If it is something recoverable like hitting the rate limit, i can look into adding code to automatically retry after waiting for the rate limit to reset - or i could at least display a more descriptive error message.

**Comment by nimuxoha** [comment]
Got something. It's a `503 Service Unavailable` for the MB ws2 requests that failed.

I opened exactly 12 magicisrc tabs from Harmony. No login on magicisrc yet.
4 of them failed in total.  The ones that failed indicated in response headers:
```
x-mb-rate-limiter: lua
x-ratelimit-zone: per-ip
```

The requests that succeeded looked like this:
```
x-cache-status: MISS
x-ratelimit-limit: 1200
x-ratelimit-remaining: 557
x-ratelimit-reset: 1744396474
x-runtime: 0.048336
```
 
zas explained these a few years ago:
https://community.metabrainz.org/t/what-do-the-x-ratelimit-headers-mean-and-how-should-they-be-used/259737/2

> (if this has happened to you, you might be able to contact musicbrainz to get this cleared).

I'm doubtful that's the case for me as I'm quite an active editor and rarely hit the rate-limit on the MB website unless I literally open hundreds of tabs in quick succession. So this problem seems limited to the API.  :(

**Comment by kepstin** [comment]
This is unfortunate :/ Good to know the specific status code is 503 at least.

Just to confirm - do the *failed* requests also the `x-ratelimit-reset` header, or only the succeeded ones? If the failed ones have that, I might be able to be a bit smarter about the retry timing when i hit an error.

Note that the numbers in `x-ratelimit-*` headers on the working request are actually for the global ratelimit (i.e. musicbrainz.org only allows a total of 1200 requests every 2 seconds for anyone regardless of ip). But the failed request you showed is from the "per-ip" zone, indicating that you've exceeded the "average 1 request per second" per-ip limit, and that's not something I've ever managed to do when testing :/

With the current implementation of magicisrc, I strongly recommend that you only open a single magicisrc tab at a time, and it might be helpful to wait for a second after the isrc submission completes before you open another magicisrc tab.

I definitely will look into adding some retry logic / rate limiting into magicisrc. This probably means that I'll have to show a "loading" screen for longer in some cases. I'm not sure whether or not I'll be able to coordinate this across multiple magicisrc tabs. It looks like there are some modern browser apis - e.g. the [Web Locks API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API) - which make this possible to do nowadays.

**Comment by nimuxoha** [comment]
> Just to confirm - do the _failed_ requests also the `x-ratelimit-reset` header, or only the succeeded ones? If the failed ones have that, I might be able to be a bit smarter about the retry timing when i hit an error.

No but there is a `retry-after` header with a number as value. So far I've seen ones with `0`, `1` or `2`

**Comment by kepstin** [comment]
I've done some initial work on error recovery and rate limiting which is now live on https://magicisrc-beta.kepstin.ca/ The approach I used is based on what MusicBrainz Picard does, which has automatic adaptation of the delay between requests, so hopefully it won't break if you're using MagicISRC at the same time as some other tool using the MusicBrainz API like Picard or beets. I've also improved the error display in case the request still fails even after being retried.

I was able to use [Web Locks API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API) to synchronize the rate limiter across multiple tabs, so multiple MagicISRC tabs will share a single rate limit.

There's still a bit more work that needs to be done - I still need to run the final ISRC submission through the rate limiter, and I need to verify that the code restructuring didn't break any templates.

**Comment by nimuxoha** [comment]
Awesome! So quick. I'll be using the beta from now on and see how it well it works.

_Edit:_
Can't even login on the beta :( 

```
(index):171 New location: https://magicisrc-beta.kepstin.ca/
(index):177 poppedState null
(index):1100 Uncaught ReferenceError: doLogin is not defined
    at HTMLButtonElement.onclick ((index):1100:2)
onclick @ (index):1100
```

**Comment by kepstin** [comment]
Well, missed that in my testing - I happened to be already logged in :) I know what happened there, that's one of the template breakages that I was worried might happen. I'll go through and double-check all the variable references in templates soon.

**Comment by kepstin** [comment]
I believe I have corrected the remaining errors regarding template rendering; please let me know if you run into any other issues on the magicisrc-beta server.

**Comment by nimuxoha** [comment]
Still not much luck. Login works but upon submitting it shows the animation endlessly and logs an error:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0') 
at buildISRCXML (?isrc1=CH6541778173&....1edb073dc5ab:651:40) 
at postISRCs (?isrc1=CH6541778173&...1edb073dc5ab:615:13) 
at doSubmitISRCs (?isrc1=CH6541778173&...-1edb073dc5ab:602:3) 
at HTMLButtonElement.onclick (?isrc1=CH6541778173&...b5-1edb073dc5ab:1:1)
```

**Comment by kepstin** [comment]
I'm still working on this… I hope to be able to finish and properly test some further updates this weekend.

**Comment by kepstin** [comment]
I've updated the https://magicisrc-beta.kepstin.ca/ site with a new version that has been more thoroughly tested - you should no longer be seeing submission errors. It now applies the rate limiting and retries on both loading releases and submitting ISRCs. Please test this out and let me know if it's working for you.

**Comment by nimuxoha** [comment]
I'm afraid it's still not fully working. Although it does claim "The ISRCs have been successfully submitted." the console shows an error and indeed no edit was created:

```
TypeError: Cannot read properties of undefined (reading 'recording')
at buildISRCMetadata (?isrc1=UKR6V2073434& .. 93f1a35aba3e:656:54)
at doSubmitISRCs (?isrc1=UKR6V2073434&93f1a35aba3e:624:22)
at HTMLButtonElement.onclick (?mbid=94d7117c-da6a -... cf-93f1a35aba3e:1:1)
```

**Comment by kepstin** [comment]
Ah, interesting… i was worried about whether I was correctly handling releases *with* pregap tracks, and made an error where it's not correctly handling releases *without* pregap tracks.

Additionally, some of the error handling was incorrect, which might be why it was still showing the success page. I'm still looking into that.

After making some updates, I was able to successfully submit the ISRCs to the release where you hit that error: https://beta.musicbrainz.org/edit/124974292 and those updates are live now.

**Comment by nimuxoha** [comment]
Nice it really seems to work in general now. But I'm still getting an error every time even when the submission was actually successful:
`When submitting ISRCs: Error: XML response has unexpected format` 

Web console:
```
Error: XML response has unexpected format
at parseXMLPostResponse (mbFetch.js:111:11)
at MbFetch.submitISRCs (mbFetch.js:317:12)
at async doSubmitISRCs (?isrc1=UKR6V2073438&...8267c674e458:626:22)
```

_Edit:_
The XML is just an "OK"
```
<?xml version="1.0" encoding="UTF-8"?>
<metadata xmlns="http://musicbrainz.org/ns/mmd-2.0#"><message><text>OK</text></message></metadata>
```

_Edit 2:_
Oh, and I still managed to get a "Failed to fetch" for one of them but accidentally closed the tab :/

_Edit 3:_
Out of 25 submission 1 failed with 503 and `Failed to fetch`

Full console output:
```
VM311:163 New location: https://magicisrc-beta.kepstin.ca/?isrc1=UKACT1912651&isrc2=UKACT1912652&musicbrainzid=f2c148c2-185e-498f-a4be-368e9df2f680&edit-note=Import+ISRCs+from+https%3A%2F%2Fwww.beatport.com%2Frelease%2Fbulldozer%2F2689105+to+https%3A%2F%2Fmusicbrainz.org%2Frelease%2Ff2c148c2-185e-498f-a4be-368e9df2f680
VM311:169 poppedState null
mbFetch.js:186 MbFetch: last request was 108.00019538402557 ms ago, waiting 891.9998046159744 ms before starting another one
mbFetch.js:212 MbFetch: back off; delay 1000 -> 1000
VM311:305 [null] [Array(2)]
mbFetch.js:305 <metadata xmlns="http://musicbrainz.org/ns/mmd-2.0#"><recording-list><recording id="78b80212-98cb-460e-931c-8a7cb71d6059"><isrc-list count="1"><isrc id="UKACT1912651"/></isrc-list></recording><recording id="648f4d73-0cc7-47b4-aadd-02a97924a811"><isrc-list count="1"><isrc id="UKACT1912652"/></isrc-list></recording></recording-list><edit-note>Import ISRCs from https://www.beatport.com/release/bulldozer/2689105 to https://musicbrainz.org/release/f2c148c2-185e-498f-a4be-368e9df2f680</edit-note></metadata>
mbFetch.js:189 MbFetch: last request was 1910.1002441644669 ms ago, starting another one
?isrc1=UKACT1912651&isrc2=UKACT1912652&edit-note=Import+ISRCs+from+https%3A%2F%2Fwww.beatport.com%2Frelease%2Fbulldozer%2F2689105+to+https%3A%2F%2Fmusicbrainz.org%2Frelease%2Ff2c148c2-185e-498f-a4be-368e9df2f680&mbid=f2c148c2-185e-498f-a4be-368e9df2f680:1 Access to fetch at 'https://musicbrainz.org/ws/2/recording/?client=kepstin-magicisrc-beta' from origin 'https://magicisrc-beta.kepstin.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
mbFetch.js:230 
            
            
           POST https://musicbrainz.org/ws/2/recording/?client=kepstin-magicisrc-beta net::ERR_FAILED 503 (Service Unavailable)
#fetchInternal @ mbFetch.js:230
await in #fetchInternal
(anonymous) @ mbFetch.js:255
VM311:776 When submitting ISRCs: TypeError: Failed to fetch
VM311:777 TypeError: Failed to fetch
    at #fetchInternal (mbFetch.js:230:35)
renderError @ VM311:777
doSubmitISRCs @ VM311:594
await in doSubmitISRCs
onclick @ ?isrc1=UKACT1912651&isrc2=UKACT1912652&edit-note=Import+ISRCs+from+https%3A%2F%2Fwww.beatport.com%2Frelease%2Fbulldozer%2F2689105+to+https%3A%2F%2Fmusicbrainz.org%2Frelease%2Ff2c148c2-185e-498f-a4be-368e9df2f680&mbid=f2c148c2-185e-498f-a4be-368e9df2f680:1
(anonymous) @ VM694:1
(anonymous) @ VM694:1

```

**Comment by kepstin** [comment]
Yeah, the `Error: XML response has unexpected format` is the last thing I'm still working on. It's supposed to be checking the response to see if the "OK" is present.

It looks like the `Access to fetch at 'https://musicbrainz.org/ws/2/recording/?client=kepstin-magicisrc-beta' from origin 'https://magicisrc-beta.kepstin.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` bit is the actual problem here, the web browser is preventing magicisrc from reading the response to the ISRC submission request because the musicbrainz api doesn't include the extra header that says its ok to do so. I'll continue working on this.

It looks like because of this problem, magicisrc wasn't able to see that your isrc submission hit a "503" error, and so the automatic retry didn't kick in.
